server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: semua route balik ke index.html, react-router yang urus sisanya.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
